image:
  - Visual Studio 2015
  - Ubuntu

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
#  APPVEYOR_RDP_PASSWORD: "/@}D9G7+mXRQNaqV"

skip_commits:
  files:
    - '**/*.md'

build: off

#before_test:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: cinst pester
  - sh: git clone https://github.com/bats-core/bats-core.git
  - sh: pushd bats-core
  - sh: ./install.sh /usr/local
  - sh: popd

test_script:
  - ps: |
      $testResultsFile = ".\TestsResults.xml"
      $res = Invoke-Pester -Path .\tests -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
      $resultsUploadUrl = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
      (New-Object 'System.Net.WebClient').UploadFile($resultsUploadUrl, (Resolve-Path $testResultsFile))
      if ($res.FailedCount -gt 0) { 
          throw "$($res.FailedCount) tests failed."
      }
  # checks if code from documentation ok
  - ps: iwr -useb https://raw.githubusercontent.com/boxforming/base/master/scripts/boxforming.psm1 | iex
  - ps: New-ClientAuthCert -Username test
  - sh: bats tests
  # checks if code from documentation ok
  - sh: source <(cat scripts/boxforming.sh)
  - sh: new_client_auth_cert
